<a href="https://colab.research.google.com/github/vkurpmax/Manipulator-Robot/blob/main/Test/Colab_Manipulator_20230527.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
cp -r '/content/drive/MyDrive/Politeknik Negeri Ujung Pandang/Semester 8/Colab/Tutor5a_annotation/'* '/content/drive/MyDrive/Politeknik Negeri Ujung Pandang/Semester 8/Colab/Tutor5c_training/'

In [ ]:
rm -r '/content/yolo_data'

rmdir: unrecognized option '--r'
Try 'rmdir --help' for more information.


In [ ]:
!dir

 Volume in drive F is Maharashtra
 Volume Serial Number is 1EA9-0BFE

 Directory of F:\Python Lab\yolov8\manipulator

26/05/2023  18:41    <DIR>          .
26/05/2023  11:39    <DIR>          ..
26/05/2023  11:39                42 .gitignore
26/05/2023  18:25    <DIR>          .ipynb_checkpoints
26/05/2023  13:41                92 curdir.py
26/05/2023  13:31    <DIR>          Dataset
26/05/2023  16:20               438 dataset.yaml
26/05/2023  11:39    <DIR>          Lib
26/05/2023  18:12               578 main.py
26/05/2023  13:39               113 mkdir.py
26/05/2023  11:39               214 pyvenv.cfg
26/05/2023  17:53    <DIR>          Scripts
26/05/2023  14:07    <DIR>          share
26/05/2023  14:23    <DIR>          Train_6
26/05/2023  14:20             2.943 train_test_split.py
26/05/2023  18:41            17.164 Untitled.ipynb
26/05/2023  17:40         6.534.387 yolov8n.pt
26/05/2023  18:40        22.573.363 yolov8s.pt
25/05/2023  05:28       136.867.539 yolov8x.pt
26/05/2023

In [ ]:
%cd manipulator/

F:\Python Lab\yolov8\manipulator


In [11]:
import locale
locale.getpreferredencoding = lambda: "UTF-8"

In [2]:
# Pip install (recommended)

!pip install ultralytics

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 591.4/591.4 kB 12.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 206.5/206.5 kB 28.7 MB/s eta 0:00:00


In [3]:
## importing required libraries
import os
import shutil
import random

!pip install tqdm --upgrade
from tqdm.notebook import tqdm

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [4]:
train_path_img = "./yolo_data/images/train/"
train_path_label = "./yolo_data/labels/train/"
val_path_img = "./yolo_data/images/val/"
val_path_label = "./yolo_data/labels/val/"
test_path = "./yolo_data/test"

In [5]:
'''
Split the dataset into train and test and creates the train.txt and test.tx with
the respective path of the images in each folder
'''

def train_test_split(path,neg_path=None, split = 0.2):
    print("------ PROCESS STARTED -------")


    files = list(set([name[:-4] for name in os.listdir(path)])) ## removing duplicate names i.e. counting only number of images
    

    print (f"--- This folder has a total number of {len(files)} images---")
    random.seed(42)
    random.shuffle(files)

    test_size = int(len(files) * split)
    train_size = len(files) - test_size

    ## creating required directories

    os.makedirs(train_path_img, exist_ok = True)
    os.makedirs(train_path_label, exist_ok = True)
    os.makedirs(val_path_img, exist_ok = True)
    os.makedirs(val_path_label, exist_ok = True)

    
    ### ----------- copying images to train folder
    for filex in tqdm(files[:train_size]):
      if filex == 'classes':
          continue
      shutil.copy2(path + filex + '.png',f"{train_path_img}/" + filex + '.png' )
      shutil.copy2(path + filex + '.txt', f"{train_path_label}/" + filex + '.txt')
        
    

    print(f"------ Training data created with 80% split {len(files[:train_size])} images -------")
    
    if neg_path:
        neg_images = list(set([name[:-4] for name in os.listdir(neg_path)])) ## removing duplicate names i.e. counting only number of images
        for filex in tqdm(neg_images):
            shutil.copy2(neg_path+filex+ ".png", f"{train_path_img}/" + filex + '.png')
            
        print(f"------ Total  {len(neg_images)} negative images added to the training data -------")
    
        print(f"------ TOTAL Training data created with {len(files[:train_size]) + len(neg_images)} images -------")
    


    ### copytin images to validation folder
    for filex in tqdm(files[train_size:]):
      if filex == 'classes':
          continue
      # print("running")
      shutil.copy2(path + filex + '.png', f"{val_path_img}/" + filex + '.png' )
      shutil.copy2(path + filex + '.txt', f"{val_path_label}/" + filex + '.txt')

    print(f"------ Testing data created with a total of {len(files[train_size:])} images ----------")
    
    print("------ TASK COMPLETED -------")

## spliting the data into train-test and creating train.txt and test.txt files
# train_test_split('/content/drive/MyDrive/custom_notebooks/yolo_data/')

### for label_tag
train_test_split('/content/drive/MyDrive/Politeknik Negeri Ujung Pandang/Semester 8/Colab/Tutor5c_training/data/') ### without negative images
# train_test_split('./data/','./negative_images/') ### if you want to feed negative images

------ PROCESS STARTED -------
--- This folder has a total number of 49 images---


  0%|          | 0/40 [00:00<?, ?it/s]

------ Training data created with 80% split 40 images -------


  0%|          | 0/9 [00:00<?, ?it/s]

------ Testing data created with a total of 9 images ----------
------ TASK COMPLETED -------


In [6]:
import ultralytics
ultralytics.checks()

Ultralytics YOLOv8.0.109 🚀 Python-3.10.11 torch-2.0.1+cu118 CUDA:0 (Tesla T4, 15102MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 23.5/78.2 GB disk)


In [7]:
from ultralytics import YOLO

In [8]:
#!yolo task=detect mode=train model=yolov8s.pt data='/content/drive/MyDrive/Politeknik Negeri Ujung Pandang/Semester 8/Colab/Tutor5a_annotation/dataset.yaml' epochs=10 imgsz=640 batch=8 project='/content/drive/MyDrive/Politeknik Negeri Ujung Pandang/Semester 8/Colab/Tutor5a_annotation/training_results' name=rubik_detector

# Load a model
#model = YOLO('/content/drive/MyDrive/Politeknik Negeri Ujung Pandang/Semester 8/Colab/yolov8x.pt')  # build a new model from YAML
#model = YOLO('yolov8n.yaml')  # build a new model from YAML
model = YOLO('yolov8m.pt')

# Train the model
results = model.train(data='/content/drive/MyDrive/Politeknik Negeri Ujung Pandang/Semester 8/Colab/Tutor5c_training/dataset.yaml', epochs=100, imgsz=640, batch=16, project='/content/drive/MyDrive/Politeknik Negeri Ujung Pandang/Semester 8/Colab/Tutor5c_training/training_results', name='rubik_detector')

100%|██████████| 49.7M/49.7M [00:00<00:00, 208MB/s]
Ultralytics YOLOv8.0.109 🚀 Python-3.10.11 torch-2.0.1+cu118 CUDA:0 (Tesla T4, 15102MiB)
yolo/engine/trainer: task=detect, mode=train, model=yolov8m.pt, data=/content/drive/MyDrive/Politeknik Negeri Ujung Pandang/Semester 8/Colab/Tutor5c_training/dataset.yaml, epochs=100, patience=50, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=/content/drive/MyDrive/Politeknik Negeri Ujung Pandang/Semester 8/Colab/Tutor5c_training/training_results, name=rubik_detector, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=0, resume=False, amp=True, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, sho

In [ ]:
!scp -r /content/runs '/content/gdrive/MyDrive/Politeknik Negeri Ujung Pandang/Semester 8/Colab/Tutor5c_training'

cp: cannot create directory '/content/gdrive/MyDrive/Politeknik Negeri Ujung Pandang/Semester 8/Colab/Tutor5c_training': No such file or directory


In [ ]:
!zip -r /content/runs.zip /content/runs

  adding: content/runs/ (stored 0%)
  adding: content/runs/detect/ (stored 0%)
  adding: content/runs/detect/predict/ (stored 0%)
  adding: content/runs/detect/predict/img0004.png (deflated 1%)


In [ ]:
files.download('/content/runs.zip')

In [30]:
#!yolo task=detect mode=predict model='/content/drive/MyDrive/Politeknik Negeri Ujung Pandang/Semester 8/Colab/Tutor5a_annotation/training_results/rubik_detector/weights/best.pt' conf=0.55 source='/content/drive/MyDrive/Politeknik Negeri Ujung Pandang/Semester 8/Colab/Tutor5a_annotation/test_images'
import cv2 as cv
from google.colab.patches import cv2_imshow
from ultralytics import YOLO

# Load a model
#model = YOLO('yolov8n.pt')  # load an official model
model = YOLO('/content/drive/MyDrive/Politeknik Negeri Ujung Pandang/Semester 8/Colab/Tutor5c_training/training_results/rubik_detector5/weights/best.pt')  # load a custom model

# Predict with the model
results = model(source='/content/drive/MyDrive/Politeknik Negeri Ujung Pandang/Semester 8/Colab/Tutor5c_training/test_images', conf=0.55, save=True, save_txt=True, show=True, show_labels=True)  # predict on an image

WARNING ⚠️ Environment does not support cv2.imshow() or PIL Image.show()


image 1/1 /content/drive/MyDrive/Politeknik Negeri Ujung Pandang/Semester 8/Colab/Tutor5c_training/test_images/img0004.png: 384x640 1 rubik, 1 base, 26.5ms
Speed: 1.5ms preprocess, 26.5ms inference, 1.8ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict6
1 label saved to runs/detect/predict6/labels


In [31]:
for result in results:
    boxes = result.boxes  # Boxes object for bbox outputs
    masks = result.masks  # Masks object for segmentation masks outputs
    probs = result.probs  # Class probabilities for classification outputs

In [19]:
boxes.xywhn

tensor([[0.4409, 0.4924, 0.5362, 0.9848],
        [0.5226, 0.7509, 0.0865, 0.1690]], device='cuda:0')

In [20]:
boxes.xywh

tensor([[564.3179, 354.5209, 686.3728, 709.0417],
        [668.8765, 540.6740, 110.7012, 121.6899]], device='cuda:0')

In [78]:
boxes.xyxy

tensor([[221.1315,   0.0000, 907.5043, 709.0417],
        [613.5259, 479.8290, 724.2271, 601.5189]], device='cuda:0')

In [76]:
boxes.xyxy[0]

tensor([221.1315,   0.0000, 907.5043, 709.0417], device='cuda:0')

In [34]:
boxes.xyxy[0, 0]

tensor(221.1315, device='cuda:0')

In [35]:
boxes.xyxy[0, 0] + boxes.xyxy[1, 0]

tensor(834.6574, device='cuda:0')

In [79]:
import torch

#tensor = boxes.xyxy.clone().detach().requires_grad_(True)

x_img = (tensor[1,0].item() + (tensor[1,2].item() - tensor[1,0].item()) / 2) - tensor[0,0].item()
y_img = tensor[0,3].item() - (tensor[1,1].item() + (tensor[1,3].item() - tensor[1,1].item()) / 2)

print(f"{x_img:.1f}, {y_img:.1f}")

447.7, 168.4


In [85]:
x_manip = 305 - round(x_img / 689 * 268)
print(x_manip)

131


In [86]:
y_manip = 305 - round(y_img / 709 * 315.6)
print(y_manip)

230


In [16]:
!cp -r /content/runs/detect/predict3 '/content/drive/MyDrive/Politeknik Negeri Ujung Pandang/Semester 8/Colab/Tutor5c_training/output'

In [ ]:
 # Write results 
 for *xyxy, conf, cls in det: 
     if save_txt:  # Write to file 
         xywh = (xyxy2xywh(torch.tensor(xyxy).view(1, 4)) / gn).view(-1).tolist()  # normalized xywh 
         with open(txt_path + '.txt', 'a') as f: 
             f.write(('%g ' * 5 + '\n') % (cls, *xywh))  # label format 
  
     if save_img or view_img:  # Add bbox to image 
         label = '%s %.2f' % (names[int(cls)], conf) 
         plot_one_box(xyxy, im0, label=label, color=colors[int(cls)], line_thickness=3) 

NameError: ignored

In [ ]:
auto_annotate(data='/content/drive/MyDrive/Politeknik Negeri Ujung Pandang/Semester 8/Colab/Tutor5a_annotation//test_images/img0004.png', det_model='yolov8x.pt', sam_model='sam_b.pt', device='', output_dir=None):

SyntaxError: ignored

In [ ]:
from pathlib import Path

from ultralytics import YOLO
from ultralytics.vit.sam import PromptPredictor, build_sam
from ultralytics.yolo.utils.torch_utils import select_device


def auto_annotate(data='/content/drive/MyDrive/Politeknik Negeri Ujung Pandang/Semester 8/Colab/Tutor5a_annotation/test_images/img0004.png',
                  det_model='yolov8s.pt',
                  sam_model='sam_b.pt',
                  device='0', output_dir='/content/drive/MyDrive/Politeknik Negeri Ujung Pandang/Semester 8/Colab/Tutor5a_annotation/test_images/'):
    """
    Automatically annotates images using a YOLO object detection model and a SAM segmentation model.
    Args:
        data (str): Path to a folder containing images to be annotated.
        det_model (str, optional): Pre-trained YOLO detection model. Defaults to 'yolov8x.pt'.
        sam_model (str, optional): Pre-trained SAM segmentation model. Defaults to 'sam_b.pt'.
        device (str, optional): Device to run the models on. Defaults to an empty string (CPU or GPU, if available).
        output_dir (str, None, optional): Directory to save the annotated results.
            Defaults to a 'labels' folder in the same directory as 'data'.
    """
    device = select_device(device)
    det_model = YOLO(det_model)
    sam_model = build_sam(sam_model)
    det_model.to(device)
    sam_model.to(device)

    if not output_dir:
        output_dir = Path(str(data)).parent / 'labels'
    Path(output_dir).mkdir(exist_ok=True, parents=True)

    prompt_predictor = PromptPredictor(sam_model)
    det_results = det_model(data, stream=True)

    for result in det_results:
        boxes = result.boxes.xyxy  # Boxes object for bbox outputs
        class_ids = result.boxes.cls.int().tolist()  # noqa
        if len(class_ids):
            prompt_predictor.set_image(result.orig_img)
            masks, _, _ = prompt_predictor.predict_torch(
                point_coords=None,
                point_labels=None,
                boxes=prompt_predictor.transform.apply_boxes_torch(boxes, result.orig_shape[:2]),
                multimask_output=False,
            )

            result.update(masks=masks.squeeze(1))
            segments = result.masks.xyn  # noqa

            with open(str(Path(output_dir) / Path(result.path).stem) + '.txt', 'w') as f:
                for i in range(len(segments)):
                    s = segments[i]
                    if len(s) == 0:
                        continue
                    segment = map(str, segments[i].reshape(-1).tolist())
                    f.write(f'{class_ids[i]} ' + ' '.join(segment) + '\n')

In [ ]:
img = '/content/img0004.png'
model='/content/drive/MyDrive/Politeknik Negeri Ujung Pandang/Semester 8/Colab/Tutor5a_annotation/training_results/rubik_detector/weights/best.pt
results = model(img)
boxes = results[0].boxes
box = boxes[0]  # returns one box
box.xyxy

SyntaxError: ignored

In [ ]:
results.boxes()

NameError: ignored